"""Pydantic v2 request/response schemas."""

from app.schemas.assessment import (
    AnalysisDetailedPublic,
    AnalysisPublic,
    AssessmentAnalysisResponse,
    AssessmentCreate,
    AssessmentDetailedAnalysisResponse,
    AssessmentPage,
    AssessmentPublic,
    AssessmentUpdate,
    AudioRecordingPublic,
)
from app.schemas.auth import (
    LoginRequest,
    LogoutResponse,
    RefreshRequest,
    RegisterRequest,
    TokenPair,
)
from app.schemas.child import (
    ChildCreate,
    ChildPage,
    ChildPublic,
    ChildUpdate,
)
from app.schemas.exercise import (
    ExerciseAssignmentComplete,
    ExerciseAssignmentCreate,
    ExerciseAssignmentPage,
    ExerciseAssignmentPublic,
    ExerciseAssignmentUpdate,
    ExerciseCreate,
    ExercisePage,
    ExercisePublic,
    ExerciseUpdate,
)
from app.schemas.kindergarten import (
    KindergartenCreate,
    KindergartenPage,
    KindergartenPublic,
    KindergartenStats,
    KindergartenUpdate,
)
from app.schemas.notification import (
    NotificationCreate,
    NotificationPage,
    NotificationPublic,
    UnreadCountResponse,
)
from app.schemas.region import (
    RegionCreate,
    RegionPage,
    RegionPublic,
    RegionUpdate,
)
from app.schemas.stats import (
    DailyAssessmentPoint,
    KindergartenStatRow,
    RegionStat,
    RegionalStatsResponse,
    RiskDistribution,
    RolePopulation,
    SystemStatsResponse,
)
from app.schemas.user import UserPublic, UserUpdate

__all__ = [
    "AnalysisDetailedPublic",
    "AnalysisPublic",
    "AssessmentAnalysisResponse",
    "AssessmentCreate",
    "AssessmentDetailedAnalysisResponse",
    "AssessmentPage",
    "AssessmentPublic",
    "AssessmentUpdate",
    "AudioRecordingPublic",
    "ChildCreate",
    "ChildPage",
    "ChildPublic",
    "ChildUpdate",
    "DailyAssessmentPoint",
    "ExerciseAssignmentComplete",
    "ExerciseAssignmentCreate",
    "ExerciseAssignmentPage",
    "ExerciseAssignmentPublic",
    "ExerciseAssignmentUpdate",
    "ExerciseCreate",
    "ExercisePage",
    "ExercisePublic",
    "ExerciseUpdate",
    "KindergartenCreate",
    "KindergartenPage",
    "KindergartenPublic",
    "KindergartenStatRow",
    "KindergartenStats",
    "KindergartenUpdate",
    "LoginRequest",
    "LogoutResponse",
    "NotificationCreate",
    "NotificationPage",
    "NotificationPublic",
    "RefreshRequest",
    "RegionCreate",
    "RegionPage",
    "RegionPublic",
    "RegionStat",
    "RegionUpdate",
    "RegionalStatsResponse",
    "RegisterRequest",
    "RiskDistribution",
    "RolePopulation",
    "SystemStatsResponse",
    "TokenPair",
    "UnreadCountResponse",
    "UserPublic",
    "UserUpdate",
]
